[package]
name = "rust-bert-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rust_bert = "0.20"
rust-bert = "*"

elapsed = "0.1"




